baseURL = 'https://skylerlee.github.io/archives/'
languageCode = 'en-US'
title = 'ArchiX'
theme = 'enfield'
paginate = 5

[params]
  tagline = 'Nothing stands, we go deeper'
  description = 'My technical blog about thinking and coding'
  github_repo = 'https://github.com/skylerlee/archives'

[outputs]
  home = ["html"]

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
