baseURL = 'https://skylerlee.github.io/'
languageCode = 'en-US'
title = 'Archives'

[params]
  tagline = 'Keep code simple stupid'
  description = 'My technical blog about thinking and coding'
  github_repo = 'https://github.com/skylerlee/archives'

[outputs]
  home = ["html"]

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
